name: Terraform Deploy to AWS

on:
  push:
    paths:
      - 'infra/terraform/**'
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform Init
      run: terraform init
      working-directory: infra/terraform

    - name: Terraform Plan
      run: terraform plan
      working-directory: infra/terraform

    - name: Terraform Apply
      run: terraform apply -auto-approve
      working-directory: infra/terraform
